services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
    # Remove the volumes section that's causing issues
    restart: unless-stopped