"""structured records — jobs, PDPs & dashboard table group (P2-05).

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-05

Creates the *structured records* table group (design §4 "structured records" + §5.2
"Dashboard — the living PDP"): ``jobs`` · ``pdps`` · ``goals`` · ``milestones`` · ``tasks``
· ``progress_entries``. Plain relational + JSONB — **no pgvector columns** in this group.

Autogenerated from the ``app.repositories.models.jobs`` / ``.dashboard`` ORM models, then
hand-reviewed (revision renumbered to the sequential ``0004`` to match the ``0001``–``0003``
chain; DDL verified against the models — types, nullability, FKs, unique/check constraints,
indexes, cascade rules).

Design decisions encoded here:

* **Attribution: ``source`` (``user`` | ``ai``) on every mutable dashboard entity (§5.2).**
  ``goals`` / ``milestones`` / ``tasks`` / ``progress_entries`` each carry a checked
  ``source`` column, and every ``status`` vocabulary already includes ``'proposed'`` — the
  pending-approval state for AI-proposed rows — so the future "proposed-by-ai → user
  approves" workflow needs no further schema migration.
* **Checked varchar, not native ENUM** for all ``status`` / ``source`` columns (same posture
  as P2-03's ``role`` / P2-04's ``memory_type``): extending the vocabulary is a cheap
  check-constraint swap, not an ``ALTER TYPE``.
* **``jobs`` dedup key = ``(source, external_id)``** (unique). ``source_url`` is nullable,
  non-unique reference metadata (URLs redirect / carry tracking params). ``raw JSONB`` keeps
  the source payload for re-parsing without re-crawling. ``match_score`` is a nullable global
  placeholder — real per-user matching is deferred to a future ``user_job_matches`` join
  table. ``jobs`` has no ``user_id`` (shared global cache; untouched by a user-delete).
* **``tasks`` anchoring.** Every task is anchored to a ``goal_id`` (NOT NULL, cascade) and
  optionally a ``milestone_id`` (nullable). Deleting a milestone ``SET NULL``s its tasks
  (they survive under the goal); deleting the goal cascades to its tasks.
* **GDPR-delete + cascade (§4).** User-delete cascades to ``pdps`` / ``goals`` (→ ``milestones``
  → ``tasks``) / ``progress_entries``. Deleting a goal cascades to its milestones and tasks.
  ``progress_entries.goal_id`` / ``.task_id`` are ``SET NULL`` — the append-only log survives
  plan edits; only a user-delete erases it (via ``user_id`` cascade).
* **``progress_entries`` is append-only** — no ``updated_at`` column (no update path modeled).

No pgvector / functional indexes in this group, so no ``env.py`` autogenerate exclusions are
needed (unlike P2-04).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema — create the jobs / PDP / dashboard tables."""
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        # Reference/display only — NOT the dedup key (URLs redirect).
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("company", sa.String(length=512), nullable=True),
        sa.Column("location", sa.String(length=512), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        # Original crawled/source payload, kept for re-parsing without re-crawling.
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        # Global relevance placeholder — real per-user matching deferred to a future
        # user_job_matches join table.
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        # Dedup key: one row per (origin, provider listing id).
        sa.UniqueConstraint("source", "external_id", name="uq_jobs_source_external_id"),
    )
    op.create_index(op.f("ix_jobs_source_url"), "jobs", ["source_url"], unique=False)

    op.create_table(
        "pdps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("career_goal", sa.Text(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        # Structured PDP sections — enough to re-render the PDF without object storage.
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        # Nullable future object-storage pointer (no object storage wired yet).
        sa.Column("pdf_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # CASCADE: a GDPR user-delete removes the user's PDP records (§4).
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pdps_user_id"), "pdps", ["user_id"], unique=False)

    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("target_role", sa.String(length=512), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("source", sa.String(length=8), server_default="user", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('user', 'ai')",
            name="ck_goals_source",
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'active', 'completed', 'abandoned')",
            name="ck_goals_status",
        ),
        # CASCADE: a GDPR user-delete removes the user's goals (→ milestones → tasks).
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)

    op.create_table(
        "milestones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("source", sa.String(length=8), server_default="user", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('user', 'ai')",
            name="ck_milestones_source",
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'pending', 'in_progress', 'completed')",
            name="ck_milestones_status",
        ),
        # CASCADE: deleting a goal removes its milestones.
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_milestones_goal_id"), "milestones", ["goal_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        # Optional — a task may have no milestone yet.
        sa.Column("milestone_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="todo", nullable=False),
        # §5.2: "every change is attributable (source = user|ai)".
        sa.Column("source", sa.String(length=8), server_default="user", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('user', 'ai')",
            name="ck_tasks_source",
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'todo', 'in_progress', 'done', 'cancelled')",
            name="ck_tasks_status",
        ),
        # CASCADE: deleting a goal removes its tasks.
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        # SET NULL: deleting a milestone detaches its tasks (they survive under the goal).
        sa.ForeignKeyConstraint(["milestone_id"], ["milestones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_goal_id"), "tasks", ["goal_id"], unique=False)
    op.create_index(op.f("ix_tasks_milestone_id"), "tasks", ["milestone_id"], unique=False)

    op.create_table(
        "progress_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        # Optional references — SET NULL so the append-only log outlives plan edits.
        sa.Column("goal_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=8), server_default="user", nullable=False),
        # Append-only: no ``updated_at`` by design.
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('user', 'ai')",
            name="ck_progress_entries_source",
        ),
        # CASCADE: a GDPR user-delete erases the user's progress log (§4).
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        # SET NULL: the log survives the user editing/deleting the plan it refers to.
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_progress_entries_goal_id"), "progress_entries", ["goal_id"], unique=False
    )
    op.create_index(
        op.f("ix_progress_entries_task_id"), "progress_entries", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_progress_entries_user_id"), "progress_entries", ["user_id"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema — drop the structured-records tables (reverse dependency order)."""
    op.drop_index(op.f("ix_progress_entries_user_id"), table_name="progress_entries")
    op.drop_index(op.f("ix_progress_entries_task_id"), table_name="progress_entries")
    op.drop_index(op.f("ix_progress_entries_goal_id"), table_name="progress_entries")
    op.drop_table("progress_entries")
    op.drop_index(op.f("ix_tasks_milestone_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_goal_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_milestones_goal_id"), table_name="milestones")
    op.drop_table("milestones")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_pdps_user_id"), table_name="pdps")
    op.drop_table("pdps")
    op.drop_index(op.f("ix_jobs_source_url"), table_name="jobs")
    op.drop_table("jobs")
