"""knowledge and vector tables — pgvector table group (P2-04).

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-05

Creates the knowledge/vectors table group (design §4 *"Postgres + pgvector — knowledge,
memory & structured records"*): ``kb_documents`` · ``kb_chunks`` · ``user_memories``.

Autogenerated from the ``app.repositories.models.knowledge`` ORM models, then hand-reviewed
(revision renumbered to the sequential ``0003`` to match the ``0001``/``0002`` chain; the
``pgvector`` ``Vector`` import added — autogenerate emitted a fully-qualified
``pgvector.sqlalchemy.vector.VECTOR`` reference without importing the package; DDL verified
against the models — vector columns, the generated ``tsvector`` column, and the custom
``USING hnsw`` / ``USING gin`` index methods all emit correctly).

Design decisions encoded here:

* **Embedding dimension = 4096 (§6 item 3).** ``kb_chunks.embedding`` and
  ``user_memories.embedding`` are ``vector(4096)`` — the full ``Qwen/Qwen3-Embedding-8B``
  output. Fixed here in all migrations.
* **High-dimension ANN index (§6, P2 exit criterion).** 4096 dims exceed pgvector's HNSW
  cap (2000 for ``vector``, 4000 for ``halfvec``), so a plain ``vector_cosine_ops`` HNSW
  index cannot be built without changing the locked dimension. The documented
  >4000-dim pattern is used: an HNSW index over the **binary quantization** of the
  embedding (``(binary_quantize(embedding)::bit(4096)) bit_hamming_ops``). Full-precision
  ``vector(4096)`` is kept for **exact cosine** (``ORDER BY embedding <=> :q``, the P2
  exit-criterion query). These are functional/expression indexes created via raw SQL
  below (not expressible through the ORM ``Index``); HNSW (not IVFFlat) needs no training
  data — correct for tables that start empty.
* **Hybrid search groundwork (anticipated, not implemented here).**
  ``kb_chunks.content_tsv`` is a ``GENERATED ALWAYS AS (to_tsvector('english', content))
  STORED`` column with a GIN index, so the later ``llm/embeddings.py`` weighted hybrid
  query has both the vector (HNSW) and lexical (GIN) index it will scan.
* **GDPR-delete (§4).** ``kb_documents.user_id`` and ``user_memories.user_id`` cascade on
  user-delete (private CV docs + learned memories are user-scoped and erased with the
  account). ``user_memories.source_message_id`` is ``ON DELETE SET NULL`` so pruning one
  message detaches the memory rather than destroying it.

The pgvector extension is not created here (bootstrapped by the P0-07 init script); this
migration assumes the ``vector`` type already exists.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Embedding width — ``Qwen/Qwen3-Embedding-8B`` full output (§6 item 3).
EMBEDDING_DIM = 4096


def upgrade() -> None:
    """Upgrade schema — create the knowledge/vector tables."""
    op.create_table(
        "kb_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("source", sa.String(length=1024), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        # NULL → shared/curated content; set → a user's private (CV-derived) doc.
        sa.Column("user_id", sa.UUID(), nullable=True),
        # Nullable: large docs may be stored chunk-only (retrievable text in kb_chunks).
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('curated', 'user_cv', 'crawled')",
            name="ck_kb_documents_source_type",
        ),
        # CASCADE: a GDPR user-delete removes the user's private documents (§4).
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kb_documents_user_id"), "kb_documents", ["user_id"], unique=False)

    op.create_table(
        "kb_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kb_document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        # vector(4096) — fixed by Qwen/Qwen3-Embedding-8B (§6 item 3).
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=False),
        # Postgres-maintained generated tsvector (STORED) for lexical/full-text search.
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # CASCADE: deleting the parent document removes its chunks.
        sa.ForeignKeyConstraint(["kb_document_id"], ["kb_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # GIN over the generated tsvector → lexical half of the future hybrid search.
    op.create_index(
        "ix_kb_chunks_content_tsv",
        "kb_chunks",
        ["content_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    # Vector ANN index: binary-quantize HNSW (bit_hamming). 4096 dims exceed pgvector's
    # HNSW cap for vector/halfvec (2000/4000), so this is the documented high-dim pattern;
    # exact cosine still runs on the full-precision column for the P2 exit query / rerank.
    # Functional expression index → raw SQL (not expressible via op.create_index).
    op.execute(
        "CREATE INDEX ix_kb_chunks_embedding_hnsw ON kb_chunks "
        "USING hnsw ((binary_quantize(embedding)::bit(4096)) bit_hamming_ops)"
    )
    op.create_index(
        op.f("ix_kb_chunks_kb_document_id"), "kb_chunks", ["kb_document_id"], unique=False
    )

    op.create_table(
        "user_memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        # vector(4096) — same dimension as kb_chunks (§6 item 3).
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=False),
        sa.Column("memory_type", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), server_default="1.0", nullable=False),
        # References the stable app-level messages.message_id (§5.5).
        sa.Column("source_message_id", sa.String(length=32), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "memory_type IN ('preference', 'fact', 'style')",
            name="ck_user_memories_memory_type",
        ),
        # SET NULL: pruning the source message detaches the memory, does not erase it.
        sa.ForeignKeyConstraint(
            ["source_message_id"], ["messages.message_id"], ondelete="SET NULL"
        ),
        # CASCADE: a GDPR user-delete removes the user's learned memories (§4).
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Vector ANN index: binary-quantize HNSW (see the kb_chunks index above for rationale).
    op.execute(
        "CREATE INDEX ix_user_memories_embedding_hnsw ON user_memories "
        "USING hnsw ((binary_quantize(embedding)::bit(4096)) bit_hamming_ops)"
    )
    op.create_index(
        op.f("ix_user_memories_source_message_id"),
        "user_memories",
        ["source_message_id"],
        unique=False,
    )
    op.create_index(op.f("ix_user_memories_user_id"), "user_memories", ["user_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema — drop the knowledge/vector tables (reverse dependency order)."""
    op.drop_index(op.f("ix_user_memories_user_id"), table_name="user_memories")
    op.drop_index(op.f("ix_user_memories_source_message_id"), table_name="user_memories")
    # Binary-quantize HNSW functional index — drop by name (created via raw SQL).
    op.drop_index("ix_user_memories_embedding_hnsw", table_name="user_memories")
    op.drop_table("user_memories")
    op.drop_index(op.f("ix_kb_chunks_kb_document_id"), table_name="kb_chunks")
    op.drop_index("ix_kb_chunks_embedding_hnsw", table_name="kb_chunks")
    op.drop_index("ix_kb_chunks_content_tsv", table_name="kb_chunks", postgresql_using="gin")
    op.drop_table("kb_chunks")
    op.drop_index(op.f("ix_kb_documents_user_id"), table_name="kb_documents")
    op.drop_table("kb_documents")
